"""`rdl-tools fetch-fonts` — refresh the self-hosted Barlow woff2 set and website/src/css/fonts.css.

Run only when bumping the font release. The output is committed, so a clean checkout builds the
site with no third-party font request. The one subcommand that opens a socket; never runs in CI.

Fonts land in website/src/css/fonts/, not website/static/fonts/, so webpack resolves the relative
url(), applies the site baseUrl and content-hashes each file.
"""

from __future__ import annotations

import argparse
import re
import sys
import urllib.request
from collections.abc import Iterator
from pathlib import Path
from urllib.parse import urlparse

from ..spec import write_generated

TIMEOUT_SECONDS = 30


GOOGLE_CSS_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=Barlow:wght@400;500;600;700"
    "&family=Barlow+Condensed:wght@500;600;700"
    "&display=swap"
)
# The css2 API serves woff2 only to browsers it recognises; anything else gets legacy ttf.
BROWSER_UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
WANTED_SUBSETS = ("latin", "latin-ext")
OFL_URL = "https://raw.githubusercontent.com/google/fonts/main/ofl/barlow/OFL.txt"

# Every URL is checked against this list before it is fetched, so a tampered constant above
# cannot turn a build step into an arbitrary request.
ALLOWED_HOSTS = ("fonts.googleapis.com", "fonts.gstatic.com", "raw.githubusercontent.com")

HEADER = """/* Self-hosted Barlow / Barlow Condensed (SIL Open Font License 1.1 — see fonts/OFL.txt).
   Generated by `rdl-tools fetch-fonts` from the Google Fonts css2 API, latin + latin-ext only.
   Do not hand-edit: rerun the command. */
"""

Face = tuple[str, str, str, str, str]


def add_parser(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--module-dir", default=".", help="Module repo root (default: cwd)")


def fetch(url: str, *, browser: bool = False) -> bytes:
    host = urlparse(url).hostname or ""
    if host not in ALLOWED_HOSTS:
        raise ValueError(f"refusing to fetch from {host!r}; allowed hosts are {ALLOWED_HOSTS}")
    request = urllib.request.Request(url)
    if browser:
        request.add_header("User-Agent", BROWSER_UA)
    with urllib.request.urlopen(request, timeout=TIMEOUT_SECONDS) as response:
        payload: bytes = response.read()
    return payload


def parse_faces(css: str) -> Iterator[Face]:
    """Yield (family, weight, subset, woff2 url, unicode-range) for the wanted subsets.

    The `/* subset */` comment line is the only place the subset name appears, so blocks are
    identified by splitting on it.
    """
    blocks = re.split(r"/\*\s*([a-z\-]+)\s*\*/", css)
    for index in range(1, len(blocks) - 1, 2):
        subset, body = blocks[index], blocks[index + 1]
        if subset not in WANTED_SUBSETS:
            continue
        family = re.search(r"font-family:\s*'([^']+)'", body)
        weight = re.search(r"font-weight:\s*(\d+)", body)
        url = re.search(r"url\((https://[^)]+\.woff2)\)", body)
        unicode_range = re.search(r"unicode-range:\s*([^;]+);", body)
        if not (family and weight and url and unicode_range):
            continue
        yield family.group(1), weight.group(1), subset, url.group(1), unicode_range.group(1).strip()


def face_filename(family: str, weight: str, subset: str) -> str:
    return f"{family.lower().replace(' ', '-')}-{weight}-{subset}.woff2"


def font_face_block(family: str, weight: str, filename: str, unicode_range: str) -> str:
    return (
        "@font-face {\n"
        f"  font-family: '{family}';\n"
        "  font-style: normal;\n"
        f"  font-weight: {weight};\n"
        "  font-display: swap;\n"
        f"  src: url('./fonts/{filename}') format('woff2');\n"
        f"  unicode-range: {unicode_range};\n"
        "}\n"
    )


def fonts_css_text(faces: list[Face]) -> str:
    blocks = [HEADER]
    for family, weight, subset, _url, unicode_range in faces:
        blocks.append(font_face_block(family, weight, face_filename(family, weight, subset), unicode_range))
    return "\n".join(blocks)


def run(args: argparse.Namespace) -> int:
    css_dir = Path(args.module_dir).resolve() / "website" / "src" / "css"
    fonts_dir = css_dir / "fonts"
    fonts_dir.mkdir(parents=True, exist_ok=True)

    css = fetch(GOOGLE_CSS_URL, browser=True).decode("utf-8")
    faces = list(parse_faces(css))
    if not faces:
        print("No woff2 @font-face blocks found in the css2 response.", file=sys.stderr)
        return 1

    total = 0
    for family, weight, subset, url, _unicode_range in faces:
        payload = fetch(url)
        (fonts_dir / face_filename(family, weight, subset)).write_bytes(payload)
        total += len(payload)

    (fonts_dir / "OFL.txt").write_bytes(fetch(OFL_URL))
    write_generated(css_dir / "fonts.css", fonts_css_text(faces))
    print(f"Wrote {len(faces)} woff2 files ({total} bytes) and {css_dir / 'fonts.css'}")
    return 0
