"""`rdl-tools render-site-data` — everything the Docusaurus site renders, from spec/*.ttl and .env.

    rdl-tools render-site-data --module-dir . --version 0.5.7            # release
    rdl-tools render-site-data --module-dir . --check                    # CI, no writes
    rdl-tools render-site-data --module-dir . --version 0.5.7 --draft-changelog

Outputs, all committed by a release so a published module builds without Python:

    website/src/generated/site.json         config-derived facts and presentation flags
    website/src/generated/releases.json     [{id,label,date,isLatest,pinIri,notes}] newest first
    website/src/generated/{version}.json    one per release — ontology metadata and every term
    website/src/generated/index.js          barrel: {site, releases, byVersion}
    website/src/css/accent.generated.css    only when .env sets ACCENT_COLOR
    website/docs/reference.mdx              the generated reference page — never hand-edited
    changelog/v{version}.md                 a draft, and only when the file is absent

Hand-written prose lives in website/docs/_intro.mdx, which this command never writes.

`--coverage-report <path>` writes the per-term annotation coverage as JSON to a path of its own.
It is written even under `--check`: the target is a CI artifact directory, not part of the tree.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections.abc import Iterable
from pathlib import Path
from typing import Any, Protocol

from rdflib import DCTERMS, OWL, RDF, RDFS, Graph, Literal, URIRef
from rdflib.namespace import SH, SKOS, Namespace
from rdflib.term import Node

from ..colour import accent_ramp, oklch_css
from ..spec import (
    declared_prefixes,
    find_previous_pin,
    local_name,
    merge_ontology,
    merge_shapes,
    ontology_files,
    read_env,
    shape_files,
    version_key,
    write_generated,
)

VANN = Namespace("http://purl.org/vocab/vann/")

CLASS_TYPES = (OWL.Class, RDFS.Class)
PROPERTY_TYPES = (RDF.Property, OWL.ObjectProperty, OWL.DatatypeProperty)

# Reverse-lookup predicates behind a term's "Used By" list.
USED_BY_PREDICATES = (
    RDFS.domain,
    RDFS.range,
    RDFS.subClassOf,
    RDFS.subPropertyOf,
    SH.path,
    SH["class"],
    SH.node,
)

# Predicates whose objects already have their own place in the card, so "Refers To" skips them.
REFERS_TO_SKIP = (RDF.type, RDFS.subClassOf, RDFS.subPropertyOf, RDFS.domain, RDFS.range)

# An IRI in one of these vocabularies is metadata about a term, never a term this module refers to.
METADATA_NAMESPACES = (
    str(RDF),
    str(RDFS),
    str(OWL),
    str(SKOS),
    str(SH),
    str(DCTERMS),
    str(VANN),
    "http://www.w3.org/2001/XMLSchema#",
    "http://purl.org/dc/elements/1.1/",
    "http://www.w3.org/ns/prov#",
    "http://xmlns.com/foaf/0.1/",
)

DOWNLOAD_LABELS = {
    "ttl": "TTL",
    "rdf": "RDF/XML",
    "jsonld": "JSON-LD",
    "nt": "N-Triples",
}

# SHACL path modifiers, longest-binding first — see ModuleData.path_text.
PATH_MODIFIERS = (
    (SH.zeroOrMorePath, "*"),
    (SH.oneOrMorePath, "+"),
    (SH.zeroOrOnePath, "?"),
)

GENERATED_BANNER = "Generated by `rdl-tools render-site-data` — do not edit."

FRONT_MATTER_RE = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)
CHANGELOG_FILE_RE = re.compile(r"^v(\d+\.\d+\.\d+)\.md$")

Json = dict[str, Any]


class NamespaceOwner(Protocol):
    """All `diff_bullets` needs of a module: which IRIs are this module's own."""

    def is_internal(self, iri: str) -> bool: ...


def add_parser(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--module-dir", default=".", help="Module repo root (default: cwd)")
    parser.add_argument("--version", help="Release version, e.g. 0.5.7 (default: owl:versionInfo)")
    parser.add_argument("--check", action="store_true", help="Generate in memory only, report, write nothing")
    parser.add_argument(
        "--draft-changelog",
        action="store_true",
        help="Draft changelog/v{version}.md from the diff against the previous pin, if absent",
    )
    parser.add_argument("--coverage-report", help="Write the annotation-coverage report to this JSON path")


# graph reading


def pick_literal(graph: Graph, subject: Node, predicate: Node) -> str | None:
    """One literal for a predicate, preferring @en, then no language, then whatever sorts first."""
    values = [o for o in graph.objects(subject, predicate) if isinstance(o, Literal)]
    if not values:
        return None
    for wanted in ("en", None):
        for value in sorted(values, key=str):
            if (value.language or None) == wanted:
                return str(value)
    return str(sorted(values, key=str)[0])


def pick_literals(graph: Graph, subject: Node, predicate: Node) -> list[str]:
    """Every literal for a predicate, @en only when any @en exists, sorted for byte-stability."""
    values = [o for o in graph.objects(subject, predicate) if isinstance(o, Literal)]
    if not values:
        return []
    english = [v for v in values if (v.language or None) == "en"]
    chosen = english or values
    return sorted({str(v) for v in chosen})


def group(path: str) -> str:
    """Parenthesise a path expression only when composing it would otherwise reassociate it."""
    return f"({path})" if any(sep in path for sep in (" | ", " / ")) else path


def prefixed_name(iri: str, prefixes: list[tuple[str, str]]) -> str:
    """`prefix:localName` for a declared namespace, else the bare IRI."""
    best = ""
    best_prefix = None
    for prefix, uri in prefixes:
        if iri.startswith(uri) and len(uri) > len(best):
            best, best_prefix = uri, prefix
    if best_prefix is None:
        return iri
    return f"{best_prefix}:{iri[len(best) :]}"


# the module view


class ModuleData:
    """Everything read out of spec/ and .env for one module, at one version."""

    def __init__(self, module_dir: Path, version: str | None):
        self.module_dir = module_dir
        self.spec_dir = module_dir / "spec"
        self.env = read_env(module_dir)
        self.graph = merge_ontology(self.spec_dir)
        self.shapes = merge_shapes(self.spec_dir)
        self.merged = self.graph + self.shapes
        self.conflicts: list[str] = []

        ontology = next(self.graph.subjects(RDF.type, OWL.Ontology), None)
        if not isinstance(ontology, URIRef):
            print(f"No owl:Ontology subject found in {self.spec_dir}/*.ttl", file=sys.stderr)
            raise SystemExit(2)
        self.ontology_iri: URIRef = ontology

        self.title = (
            pick_literal(self.graph, ontology, DCTERMS.title) or pick_literal(self.graph, ontology, RDFS.label) or ""
        )
        self.description = (
            pick_literal(self.graph, ontology, DCTERMS.description)
            or pick_literal(self.graph, ontology, RDFS.comment)
            or ""
        )
        self.version = version or pick_literal(self.graph, ontology, OWL.versionInfo) or "0.0.0"
        self.namespace = self._namespace()
        self.prefixes = self._prefixes()
        self.term_label_source = self.env.get("TERM_LABEL_SOURCE", "localName")
        self.external_link_policy = self.env.get("EXTERNAL_LINK_POLICY", "resolve")

        self.class_iris = self._terms_of_type(CLASS_TYPES)
        self.property_iris = self._terms_of_type(PROPERTY_TYPES)
        self.term_iris = set(self.class_iris) | set(self.property_iris)

    # -- config -------------------------------------------------------------

    def _prefixes(self) -> list[tuple[str, str]]:
        """Declared prefixes in declaration order, with this module's own prefix moved last."""
        prefixes = declared_prefixes(ontology_files(self.spec_dir) + shape_files(self.spec_dir))
        module_prefix = self.namespace["prefix"]
        if module_prefix:
            own = [p for p in prefixes if p[0] == module_prefix]
            prefixes = [p for p in prefixes if p[0] != module_prefix] + own
        return prefixes

    def _namespace(self) -> dict[str, str]:
        prefix = pick_literal(self.graph, self.ontology_iri, VANN.preferredNamespacePrefix)
        uri = pick_literal(self.graph, self.ontology_iri, VANN.preferredNamespaceUri)
        return {
            "prefix": prefix or "",
            "uri": uri or self.env.get("MODULE_NAMESPACE", ""),
        }

    @property
    def namespace_uri(self) -> str:
        return self.namespace["uri"]

    @property
    def major_iri(self) -> str:
        authority = self.env.get("W3ID_AUTHORITY", "")
        return f"https://w3id.org/{authority}/{self.env.get('MODULE_SLUG', '')}/v0/ont"

    def pin_iri(self, version: str) -> str:
        """The immutable pin for a version, always from config: a derived module's ontology IRI
        sits under its upstream authority, not this module's."""
        return self.major_iri.replace("/v0/ont", f"/v{version}/ont")

    @property
    def static_base_url(self) -> str:
        """Site-relative base a download link resolves from, whatever page or origin serves it.

        Never the w3id pin IRI: that is a redirect target for RDF clients, not a static path.
        """
        base = self.env.get("WEBSITE_BASE_URL") or f"/{self.env.get('MODULE_SLUG', '')}/"
        return base if base.endswith("/") else base + "/"

    # -- terms --------------------------------------------------------------

    def _terms_of_type(self, types: tuple[URIRef, ...]) -> list[URIRef]:
        found = set()
        for rdf_type in types:
            for subject in self.graph.subjects(RDF.type, rdf_type):
                if isinstance(subject, URIRef) and self.is_internal(str(subject)):
                    found.add(subject)
        return sorted(found, key=lambda s: local_name(str(s)).lower())

    def is_internal(self, iri: str) -> bool:
        return bool(self.namespace_uri) and iri.startswith(self.namespace_uri)

    def label_for(self, iri: URIRef) -> str:
        name = local_name(str(iri))
        if self.term_label_source == "rdfsLabel" and self.is_internal(str(iri)):
            return pick_literal(self.graph, iri, RDFS.label) or name
        return name

    def ref(self, iri: URIRef, via: URIRef | None = None) -> Json:
        """A `ref` as the JSON schema defines it: identity, display label and where it links."""
        iri_str = str(iri)
        internal = self.is_internal(iri_str)
        href: str | None
        if internal:
            href = f"#{local_name(iri_str)}"
        elif self.external_link_policy == "resolve":
            href = iri_str
        else:
            href = None
        return {
            "id": local_name(iri_str),
            "label": self.label_for(iri),
            "iri": iri_str,
            "href": href,
            "external": not internal,
            "via": prefixed_name(str(via), self.prefixes) if via is not None else None,
        }

    def sorted_refs(self, iris: Iterable[URIRef]) -> list[Json]:
        return [self.ref(i) for i in sorted(set(iris), key=lambda s: local_name(str(s)).lower())]

    def definition_of(self, term: URIRef) -> tuple[str, str | None]:
        """skos:definition wins, rdfs:comment is the fallback; the source is reported."""
        definition = pick_literal(self.graph, term, SKOS.definition)
        if definition is not None:
            return definition, "skos:definition"
        comment = pick_literal(self.graph, term, RDFS.comment)
        if comment is not None:
            return comment, "rdfs:comment"
        return "", None

    def is_term_reference(self, iri: URIRef) -> bool:
        """True when an object IRI names a term rather than metadata about one."""
        iri_str = str(iri)
        if self.is_internal(iri_str):
            return iri_str in {str(t) for t in self.term_iris}
        return not any(iri_str.startswith(ns) for ns in METADATA_NAMESPACES)

    def used_by(self, term: URIRef, exclude: set[str]) -> list[Json]:
        """Named terms pointing at this one, minus refs that already have their own block."""
        found = set()
        for predicate in USED_BY_PREDICATES:
            for subject in self.merged.subjects(predicate, term):
                if not isinstance(subject, URIRef) or subject == term:
                    continue
                # Blank property shapes are skipped: Used By lists named terms only.
                if (subject in self.term_iris or not self.is_internal(str(subject))) and str(subject) not in exclude:
                    found.add(subject)
        return self.sorted_refs(found)

    def refers_to(self, term: URIRef, exclude: set[str]) -> list[Json]:
        """Term-valued objects of this term's own triples, each tagged with the predicate used."""
        found: dict[str, Json] = {}
        for predicate, obj in sorted(self.graph.predicate_objects(term), key=lambda po: (str(po[0]), str(po[1]))):
            if predicate in REFERS_TO_SKIP or not isinstance(obj, URIRef):
                continue
            if obj == term or str(obj) in exclude:
                continue
            if not self.is_term_reference(obj):
                continue
            assert isinstance(predicate, URIRef)
            found.setdefault(str(obj), self.ref(obj, via=predicate))
        return [found[key] for key in sorted(found, key=lambda i: local_name(i).lower())]

    def path_text(self, node: Node | None, depth: int = 0) -> str:
        """SPARQL-style text for a SHACL path expression: `^isPartOf`, `a / b`, `a | b`, `a+`.

        A bare IRI renders as the term's own label; anything else is a blank node with no other
        way to reach the reader.
        """
        if isinstance(node, URIRef):
            return self.label_for(node)
        if depth > 8 or node is None:  # a malformed path must not recurse forever
            return "…"
        if self.shapes.value(node, RDF.first) is not None:
            return " / ".join(group(self.path_text(item, depth + 1)) for item in self.shapes.items(node))
        inverse = self.shapes.value(node, SH.inversePath)
        if inverse is not None:
            return f"^{group(self.path_text(inverse, depth + 1))}"
        alternative = self.shapes.value(node, SH.alternativePath)
        if alternative is not None:
            return " | ".join(self.path_text(item, depth + 1) for item in self.shapes.items(alternative))
        for predicate, suffix in PATH_MODIFIERS:
            inner = self.shapes.value(node, predicate)
            if inner is not None:
                return f"{group(self.path_text(inner, depth + 1))}{suffix}"
        return "…"

    def constraints_for(self, cls: URIRef) -> list[Json]:
        """One row per sh:property of every sh:NodeShape targeting this class.

        `property` is a linkable ref only when the path is a bare IRI; `path` always carries the
        display text. `severity` is reported only when it is not SHACL's sh:Violation default.
        """
        rows: list[Json] = []
        for shape in self.shapes.subjects(SH.targetClass, cls):
            for property_shape in self.shapes.objects(shape, SH.property):
                path = self.shapes.value(property_shape, SH.path)
                if path is None:
                    continue
                range_node = None
                for predicate in (SH["class"], SH.datatype, SH.node):
                    candidate = self.shapes.value(property_shape, predicate)
                    if isinstance(candidate, URIRef):
                        range_node = candidate
                        break
                severity = self.shapes.value(property_shape, SH.severity)
                rows.append(
                    {
                        "property": self.ref(path) if isinstance(path, URIRef) else None,
                        "path": self.path_text(path),
                        "range": self.ref(range_node) if range_node is not None else None,
                        "cardinality": self._cardinality(property_shape),
                        "severity": (
                            local_name(str(severity))
                            if isinstance(severity, URIRef) and severity != SH.Violation
                            else None
                        ),
                        "message": pick_literal(self.shapes, property_shape, SH.message),
                    }
                )
        rows.sort(key=lambda row: (str(row["path"]).lower(), row["cardinality"] or ""))
        return rows

    def _cardinality(self, property_shape: Node) -> str | None:
        """`min..max`, or None when the shape declares neither — `0..*` would overstate it."""
        minimum = self.shapes.value(property_shape, SH.minCount)
        maximum = self.shapes.value(property_shape, SH.maxCount)
        if minimum is None and maximum is None:
            return None
        low = int(minimum) if isinstance(minimum, Literal) else 0
        high = int(maximum) if isinstance(maximum, Literal) else "*"
        return f"{low}..{high}"

    def property_cardinality(self, prop: URIRef) -> str | None:
        """The chip beside a property heading. Omitted, and reported, when shapes disagree."""
        found = set()
        for property_shape in self.shapes.subjects(SH.path, prop):
            declared = self._cardinality(property_shape)
            if declared is not None:
                found.add(declared)
        if len(found) == 1:
            return found.pop()
        if len(found) > 1:
            self.conflicts.append(
                f"{local_name(str(prop))}: conflicting SHACL cardinalities {sorted(found)} — chip omitted"
            )
        return None

    # -- assembled records --------------------------------------------------

    def class_record(self, cls: URIRef) -> Json:
        definition, source = self.definition_of(cls)
        super_classes = [o for o in self.graph.objects(cls, RDFS.subClassOf) if isinstance(o, URIRef)]
        sub_classes = [s for s in self.graph.subjects(RDFS.subClassOf, cls) if isinstance(s, URIRef)]
        own_blocks = {str(i) for i in list(super_classes) + list(sub_classes)}
        return {
            "id": local_name(str(cls)),
            "label": self.label_for(cls),
            "iri": str(cls),
            "definition": definition,
            "definitionSource": source,
            "examples": pick_literals(self.graph, cls, SKOS.example),
            "guidance": pick_literals(self.graph, cls, SKOS.editorialNote),
            "scope": pick_literals(self.graph, cls, SKOS.scopeNote),
            "superClasses": self.sorted_refs(super_classes),
            "subClasses": self.sorted_refs(sub_classes),
            "constraints": self.constraints_for(cls),
            "usedBy": self.used_by(cls, exclude={str(i) for i in sub_classes}),
            "refersTo": self.refers_to(cls, exclude=own_blocks),
        }

    def property_record(self, prop: URIRef) -> Json:
        definition, source = self.definition_of(prop)
        domain = next((o for o in self.graph.objects(prop, RDFS.domain) if isinstance(o, URIRef)), None)
        range_ = next((o for o in self.graph.objects(prop, RDFS.range) if isinstance(o, URIRef)), None)
        super_properties = [o for o in self.graph.objects(prop, RDFS.subPropertyOf) if isinstance(o, URIRef)]
        own_blocks = {str(i) for i in super_properties}
        own_blocks |= {str(i) for i in (domain, range_) if i is not None}
        return {
            "id": local_name(str(prop)),
            "label": self.label_for(prop),
            "iri": str(prop),
            "definition": definition,
            "definitionSource": source,
            "examples": pick_literals(self.graph, prop, SKOS.example),
            "guidance": pick_literals(self.graph, prop, SKOS.editorialNote),
            "scope": pick_literals(self.graph, prop, SKOS.scopeNote),
            "domain": self.ref(domain) if domain is not None else None,
            "range": self.ref(range_) if range_ is not None else None,
            "subPropertyOf": self.sorted_refs(super_properties),
            "symmetric": (prop, RDF.type, OWL.SymmetricProperty) in self.graph,
            "cardinality": self.property_cardinality(prop),
            "usedBy": self.used_by(prop, exclude=set()),
            "refersTo": self.refers_to(prop, exclude=own_blocks),
        }

    def license_record(self) -> Json | None:
        license_iri = next(self.graph.objects(self.ontology_iri, DCTERMS.license), None)
        if license_iri is None:
            return None
        if isinstance(license_iri, Literal):
            return {"label": str(license_iri), "href": None}
        label = local_name(str(license_iri))
        return {"label": label[:-5] if label.endswith(".html") else label, "href": str(license_iri)}

    def release_date(self) -> str | None:
        source = self.env.get("RELEASE_DATE_SOURCE", "dcterms:modified")
        predicate = {"dcterms:modified": DCTERMS.modified, "dcterms:created": DCTERMS.created}.get(
            source, DCTERMS.modified
        )
        return pick_literal(self.graph, self.ontology_iri, predicate)

    def downloads(self, version: str) -> list[Json]:
        """Only formats present on disk get a button, not every format DOWNLOAD_FORMATS asks for."""
        formats = [f.strip() for f in self.env.get("DOWNLOAD_FORMATS", "ttl").split(",") if f.strip()]
        pin_dir = self.module_dir / "website" / "static" / f"v{version}" / "ont"
        base = f"{self.static_base_url}v{version}/ont"
        downloads = [
            {"label": DOWNLOAD_LABELS.get(fmt, fmt.upper()), "href": f"{base}/ont.{fmt}"}
            for fmt in formats
            if fmt in DOWNLOAD_LABELS and (pin_dir / f"ont.{fmt}").exists()
        ]
        # render-docs copies spec/*.generated.ttl into every artifact tree as ledger.ttl.
        if (pin_dir / "ledger.ttl").exists():
            downloads.append({"label": "Ledger", "href": f"{base}/ledger.ttl"})
        return downloads

    def version_payload(self, version: str, date: str | None, is_latest: bool, notes: list[str]) -> Json:
        version_iri = next(self.graph.objects(self.ontology_iri, OWL.versionIRI), None)
        prior = next(self.graph.objects(self.ontology_iri, OWL.priorVersion), None)
        return {
            "id": version,
            "label": f"v{version}",
            "date": date,
            "isLatest": is_latest,
            "ontology": {
                "iri": str(self.ontology_iri),
                "versionIri": str(version_iri) if version_iri is not None else self.pin_iri(version),
                "priorVersionIri": str(prior) if prior is not None else None,
                "majorIri": self.major_iri,
                "pinIri": self.pin_iri(version),
                "title": self.title,
                "description": self.description,
                "publisher": pick_literal(self.graph, self.ontology_iri, DCTERMS.publisher),
                "created": pick_literal(self.graph, self.ontology_iri, DCTERMS.created),
                "modified": pick_literal(self.graph, self.ontology_iri, DCTERMS.modified),
                "versionInfo": pick_literal(self.graph, self.ontology_iri, OWL.versionInfo),
                "license": self.license_record(),
                "namespace": self.namespace,
            },
            "namespaces": [{"prefix": p, "uri": u} for p, u in self.prefixes],
            "counts": {"classes": len(self.class_iris), "properties": len(self.property_iris)},
            "downloads": self.downloads(version),
            "changelog": notes,
            "classes": [self.class_record(c) for c in self.class_iris],
            "properties": [self.property_record(p) for p in self.property_iris],
        }

    def site_payload(self, latest_version: str) -> Json:
        return {
            "moduleSlug": self.env.get("MODULE_SLUG", ""),
            "title": self.title,
            "tagline": self.description,
            "brandSubtitle": self.env.get("BRAND_SUBTITLE", "Reference Data Library"),
            "majorIri": self.major_iri,
            "pinIriPattern": self.major_iri.replace("/v0/ont", "/v{version}/ont"),
            "latestVersion": latest_version,
            "latestVersionLabel": f"v{latest_version}",
            "defaultColorMode": self.env.get("DEFAULT_COLOR_MODE", "light"),
            "termLabelSource": self.term_label_source,
            "externalLinkPolicy": self.external_link_policy,
            "showFooter": self.env.get("SHOW_FOOTER", "false").lower() == "true",
            "accentColor": self.env.get("ACCENT_COLOR", ""),
        }


# releases


def parse_changelog(path: Path) -> tuple[str | None, list[str]]:
    """(date, bullets) from a changelog/v*.md file. Front matter is optional."""
    text = path.read_text(encoding="utf-8")
    date = None
    match = FRONT_MATTER_RE.match(text)
    if match:
        for line in match.group(1).splitlines():
            key, _, value = line.partition(":")
            if key.strip() == "date":
                date = value.strip().strip("\"'") or None
        text = text[match.end() :]
    bullets = [re.sub(r"^[-*]\s+", "", line).strip() for line in text.splitlines() if re.match(r"^[-*]\s+", line)]
    return date, bullets


def pin_release_date(static_dir: Path, version: str, module: ModuleData) -> str | None:
    """Last resort for a historical release's date: the date stamped into its published pin."""
    pin = static_dir / f"v{version}" / "ont" / "ont.ttl"
    if not pin.exists():
        return None
    graph = Graph()
    try:
        graph.parse(pin, format="turtle")
    except Exception:  # a malformed old pin must not break the build
        return None
    ontology = next(graph.subjects(RDF.type, OWL.Ontology), None)
    if ontology is None:
        return None
    source = module.env.get("RELEASE_DATE_SOURCE", "dcterms:modified")
    predicate = DCTERMS.created if source == "dcterms:created" else DCTERMS.modified
    return pick_literal(graph, ontology, predicate)


def collect_releases(module: ModuleData, version: str) -> list[Json]:
    """Every release the repo knows about — changelog files, published pins and the one being cut."""
    changelog_dir = module.module_dir / "changelog"
    static_dir = module.module_dir / "website" / "static"

    versions: set[str] = {version}
    notes: dict[str, list[str]] = {}
    dates: dict[str, str | None] = {}

    if changelog_dir.is_dir():
        for path in sorted(changelog_dir.glob("v*.md")):
            match = CHANGELOG_FILE_RE.match(path.name)
            if not match:
                continue
            found = match.group(1)
            versions.add(found)
            dates[found], notes[found] = parse_changelog(path)

    if static_dir.is_dir():
        for child in static_dir.iterdir():
            if child.is_dir() and re.match(r"^v\d+\.\d+\.\d+$", child.name):
                versions.add(child.name[1:])

    ordered = sorted(versions, key=version_key, reverse=True)
    latest = ordered[0] if ordered else version
    releases = []
    for found in ordered:
        date = dates.get(found)
        if date is None:
            date = module.release_date() if found == version else pin_release_date(static_dir, found, module)
        releases.append(
            {
                "id": found,
                "label": f"v{found}",
                "date": date,
                "isLatest": found == latest,
                "pinIri": module.pin_iri(found),
                "notes": notes.get(found, []),
            }
        )
    return releases


# emitters


def json_text(payload: object) -> str:
    return json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=False) + "\n"


def js_identifier(version: str) -> str:
    return "v" + re.sub(r"[^0-9A-Za-z]", "_", version)


def barrel_text(versions: list[str]) -> str:
    imports = "\n".join(f"import {js_identifier(v)} from './{v}.json';" for v in versions)
    entries = "\n".join(f"  '{v}': {js_identifier(v)}," for v in versions)
    return (
        f"// {GENERATED_BANNER}\n"
        "import site from './site.json';\n"
        "import releases from './releases.json';\n"
        f"{imports}\n"
        "\n"
        "export const byVersion = {\n"
        f"{entries}\n"
        "};\n"
        "\n"
        "export {site, releases};\n"
        "export default {site, releases, byVersion};\n"
    )


def accent_css_text(accent: str) -> str:
    """The --rdl-accent-* token overrides for one accent hex, light and dark.

    Every component reads var(--rdl-*), so these are the whole recolouring surface. Infima's
    primary ramp is remapped from the same stops so built-in theme chrome matches.
    """
    ramp = accent_ramp(accent)
    ramp_lines = "\n".join(f"  --rdl-accent-{stop}: {oklch_css(ramp[stop])};" for stop in sorted(ramp))
    return f"""/* {GENERATED_BANNER}
   Derived from ACCENT_COLOR={accent} in .env. Delete the key to fall back to the Industry steel
   values in rdl.css. */

:root {{
{ramp_lines}

  --rdl-accent: var(--rdl-accent-600);
  --rdl-accent-strong: var(--rdl-accent-700);
  --rdl-accent-hover: var(--rdl-accent-600);
  --rdl-accent-text: var(--rdl-accent-700);
  --rdl-accent-tint: var(--rdl-accent-100);
  --rdl-accent-tint-text: var(--rdl-accent-800);

  --ifm-color-primary: var(--rdl-accent-600);
  --ifm-color-primary-dark: var(--rdl-accent-700);
  --ifm-color-primary-darker: var(--rdl-accent-700);
  --ifm-color-primary-darkest: var(--rdl-accent-800);
  --ifm-color-primary-light: var(--rdl-accent-500);
  --ifm-color-primary-lighter: var(--rdl-accent-400);
  --ifm-color-primary-lightest: var(--rdl-accent-300);
}}

[data-theme='dark'] {{
  --rdl-accent: var(--rdl-accent-400);
  --rdl-accent-strong: var(--rdl-accent-300);
  --rdl-accent-hover: var(--rdl-accent-200);
  --rdl-accent-text: var(--rdl-accent-300);
  --rdl-accent-tint: {oklch_css(ramp[400], alpha=0.14)};
  --rdl-accent-tint-text: var(--rdl-accent-200);

  --ifm-color-primary: var(--rdl-accent-400);
  --ifm-color-primary-dark: var(--rdl-accent-500);
  --ifm-color-primary-darker: var(--rdl-accent-500);
  --ifm-color-primary-darkest: var(--rdl-accent-600);
  --ifm-color-primary-light: var(--rdl-accent-300);
  --ifm-color-primary-lighter: var(--rdl-accent-200);
  --ifm-color-primary-lightest: var(--rdl-accent-100);
}}
"""


def escape_mdx_heading(text: str) -> str:
    """Markdown/MDX specials that would otherwise turn a term label into formatting."""
    return re.sub(r"([\\`*_{}\[\]<>])", r"\\\1", text)


def yaml_scalar(text: str) -> str:
    """A double-quoted YAML scalar: a title out of RDF can hold colons, quotes, `#` or newlines."""
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    escaped = re.sub(r"\s+", " ", escaped).strip()
    return f'"{escaped}"'


def meta_description(text: str) -> str:
    """The first paragraph only: `description` becomes the page's meta tag."""
    first = re.split(r"\n\s*\n", text.strip(), maxsplit=1)[0]
    return re.sub(r"\s+", " ", first).strip()


def reference_mdx_text(module: ModuleData, version: str) -> str:
    """The generated reference page.

    Term headings are real markdown so they land in Docusaurus's `toc` prop, and carry explicit
    `{#LocalName}` anchors, because Docusaurus otherwise lowercases case-preserving anchors.
    """
    lines: list[str | None] = [
        "---",
        f"title: {yaml_scalar(f'{module.title} v{version}')}",
        "hide_title: true",
        f"description: {yaml_scalar(meta_description(module.description))}" if module.description else None,
        "slug: /",
        "toc_max_heading_level: 3",
        "---",
        "",
        f"{{/* {GENERATED_BANNER} Hand-written prose belongs in _intro.mdx. */}}",
        "",
        "import Intro from './_intro.mdx';",
        "import {ReferenceHeader, MetadataSection, TermCard, TermBody} from '@site/src/components/rdl';",
        "",
        "<ReferenceHeader />",
        "",
        "<Intro />",
        "",
        "## Metadata {#metadata}",
        "",
        "<MetadataSection />",
    ]
    for heading, records in (("Classes", module.class_iris), ("Properties", module.property_iris)):
        if not records:
            continue
        anchor = heading.lower()
        lines += ["", f"## {heading} {{#{anchor}}}"]
        for term in records:
            term_id = local_name(str(term))
            # The card frame wraps the heading rather than replacing it: only a real markdown
            # heading reaches the `toc` prop, the left rail and the search index.
            lines += [
                "",
                f'<TermCard id="{term_id}">',
                "",
                f"### {escape_mdx_heading(module.label_for(term))} {{#{term_id}}}",
                "",
                f'<TermBody id="{term_id}" />',
                "",
                "</TermCard>",
            ]
    return "\n".join(line for line in lines if line is not None) + "\n"


def changelog_draft_text(version: str, date: str | None, bullets: list[str]) -> str:
    body = "\n".join(f"- {bullet}" for bullet in bullets) or "- _Describe this release._"
    return (
        "---\n"
        f"date: {date or ''}\n"
        "---\n"
        "\n"
        "<!-- Drafted by `rdl-tools render-site-data --draft-changelog`. Edit freely: the command\n"
        "     never overwrites an existing changelog file. These bullets are published verbatim on\n"
        f"     the Home page's \"What's new in v{version}\" list and on the Versions page. -->\n"
        "\n"
        f"{body}\n"
    )


# changelog diffing


def diff_bullets(previous: Graph, current: Graph, module: NamespaceOwner) -> list[str]:
    """Draft release notes from the graph delta against the previous published pin."""

    def terms(graph: Graph, types: tuple[URIRef, ...]) -> set[str]:
        found = set()
        for rdf_type in types:
            for subject in graph.subjects(RDF.type, rdf_type):
                if isinstance(subject, URIRef) and module.is_internal(str(subject)):
                    found.add(local_name(str(subject)))
        return found

    bullets: list[str] = []
    removed_terms: set[str] = set()
    for kind, types in (("class", CLASS_TYPES), ("property", PROPERTY_TYPES)):
        before, after = terms(previous, types), terms(current, types)
        for name in sorted(after - before):
            bullets.append(f"Added {kind} `{name}`.")
        removed = before - after
        removed_terms |= removed
        for name in sorted(removed):
            bullets.append(f"Removed {kind} `{name}`.")

    def pairs(graph: Graph, predicate: URIRef) -> set[tuple[str, str]]:
        return {
            (local_name(str(s)), local_name(str(o)))
            for s, o in graph.subject_objects(predicate)
            if isinstance(s, URIRef) and isinstance(o, URIRef) and module.is_internal(str(s))
        }

    for predicate, label in (
        (RDFS.domain, "domain"),
        (RDFS.range, "range"),
        (RDFS.subClassOf, "superclass"),
        (RDFS.subPropertyOf, "super-property"),
    ):
        before_pairs, after_pairs = pairs(previous, predicate), pairs(current, predicate)
        for subject, obj in sorted(after_pairs - before_pairs):
            bullets.append(f"`{subject}` gained {label} `{obj}`.")
        # No "lost X" bullet for a subject already reported as removed: it is implied.
        for subject, obj in sorted(before_pairs - after_pairs):
            if subject in removed_terms:
                continue
            bullets.append(f"`{subject}` lost {label} `{obj}`.")

    def definitions(graph: Graph) -> dict[str, str]:
        found: dict[str, str] = {}
        for predicate in (SKOS.definition, RDFS.comment):
            for subject, obj in graph.subject_objects(predicate):
                if isinstance(subject, URIRef) and module.is_internal(str(subject)):
                    found.setdefault(local_name(str(subject)), str(obj))
        return found

    before_defs, after_defs = definitions(previous), definitions(current)
    for name in sorted(set(before_defs) & set(after_defs)):
        if before_defs[name] != after_defs[name]:
            bullets.append(f"Reworded the definition of `{name}`.")

    def shape_rows(graph: Graph) -> set[tuple[str, str]]:
        rows = set()
        for shape in graph.subjects(SH.targetClass, None):
            target = graph.value(shape, SH.targetClass)
            for property_shape in graph.objects(shape, SH.property):
                path = graph.value(property_shape, SH.path)
                if isinstance(target, URIRef) and isinstance(path, URIRef):
                    rows.add((local_name(str(target)), local_name(str(path))))
        return rows

    before_rows, after_rows = shape_rows(previous), shape_rows(current)
    for target, path_name in sorted(after_rows - before_rows):
        bullets.append(f"Added a SHACL constraint on `{target}.{path_name}`.")
    for target, path_name in sorted(before_rows - after_rows):
        bullets.append(f"Removed the SHACL constraint on `{target}.{path_name}`.")
    return bullets


# reporting


def coverage_rows(payload: Json) -> list[Json]:
    rows = []
    for kind, singular in (("classes", "class"), ("properties", "property")):
        for term in payload[kind]:
            rows.append(
                {
                    "id": term["id"],
                    "kind": singular,
                    "definitionSource": term["definitionSource"],
                    "hasDefinition": bool(term["definition"]),
                    "hasExamples": bool(term["examples"]),
                    "hasGuidance": bool(term["guidance"]),
                    "hasScope": bool(term["scope"]),
                }
            )
    return rows


def print_coverage(rows: list[Json]) -> None:
    total = len(rows)
    if not total:
        print("Coverage: no terms found in the module namespace.")
        return

    def pct(key: str) -> str:
        count = sum(1 for row in rows if row[key])
        return f"{count}/{total} ({count * 100 // total}%)"

    fallback = [row["id"] for row in rows if row["definitionSource"] == "rdfs:comment"]
    missing = [row["id"] for row in rows if not row["hasDefinition"]]
    print(f"Annotation coverage over {total} terms (warn only):")
    print(f"  skos:definition / rdfs:comment  {pct('hasDefinition')}")
    print(f"  skos:example                    {pct('hasExamples')}")
    print(f"  skos:editorialNote              {pct('hasGuidance')}")
    print(f"  skos:scopeNote                  {pct('hasScope')}")
    if fallback:
        print(f"  falling back to rdfs:comment:   {', '.join(fallback)}")
    if missing:
        print(f"  no definition at all:           {', '.join(missing)}")


def check_drift(module: ModuleData) -> list[str]:
    """The .env-vs-RDF drift gate. The namespace is the only value duplicated between the two."""
    problems = []
    if not module.namespace_uri:
        problems.append(
            "No vann:preferredNamespaceUri on the owl:Ontology node and no MODULE_NAMESPACE in "
            ".env — the generator cannot tell which terms belong to this module."
        )
    configured_ns = module.env.get("MODULE_NAMESPACE", "")
    if configured_ns and module.namespace_uri and configured_ns != module.namespace_uri:
        problems.append(
            f"MODULE_NAMESPACE={configured_ns!r} in .env disagrees with "
            f"vann:preferredNamespaceUri={module.namespace_uri!r}."
        )
    return problems


# the command


def run(args: argparse.Namespace) -> int:
    module_dir = Path(args.module_dir).resolve()
    module = ModuleData(module_dir, args.version.lstrip("v") if args.version else None)
    version = module.version

    problems = check_drift(module)
    if problems:
        for problem in problems:
            print(f"drift gate: {problem}", file=sys.stderr)
        return 1

    releases = collect_releases(module, version)
    notes: list[str] = next((r["notes"] for r in releases if r["id"] == version), [])
    is_latest = next((r["isLatest"] for r in releases if r["id"] == version), True)
    latest_version = next((r["id"] for r in releases if r["isLatest"]), version)

    payload = module.version_payload(version, module.release_date(), is_latest, notes)
    site = module.site_payload(latest_version)
    rows = coverage_rows(payload)

    generated_dir = module_dir / "website" / "src" / "generated"
    known_versions = sorted(
        {version} | {p.stem for p in generated_dir.glob("*.json") if re.match(r"^\d+\.\d+\.\d+$", p.stem)},
        key=version_key,
        reverse=True,
    )

    # reference.mdx is one working copy: rendering a new version without a doc snapshot of the
    # last one loses it silently. See docs/adrs/ADR-003.
    previous_versions = [v for v in known_versions if v != version]
    if previous_versions:
        previous_latest = max(previous_versions, key=version_key)
        versions_json_path = module_dir / "website" / "versions.json"
        try:
            cut_versions = (
                json.loads(versions_json_path.read_text(encoding="utf-8")) if versions_json_path.exists() else []
            )
        except json.JSONDecodeError:
            cut_versions = []
        if previous_latest not in cut_versions:
            print(
                f"error: rendering v{version} would overwrite website/docs/reference.mdx while "
                f"v{previous_latest}'s docs were never snapshotted as a Docusaurus doc version.",
                file=sys.stderr,
            )
            print(
                f"Run this first, then re-run this command: "
                f"(cd website && npx docusaurus docs:version {previous_latest})",
                file=sys.stderr,
            )
            return 1

    outputs: dict[Path, str] = {
        generated_dir / "site.json": json_text(site),
        generated_dir / "releases.json": json_text(releases),
        generated_dir / f"{version}.json": json_text(payload),
        generated_dir / "index.js": barrel_text(known_versions),
        module_dir / "website" / "docs" / "reference.mdx": reference_mdx_text(module, version),
    }
    accent = module.env.get("ACCENT_COLOR", "").strip()
    accent_path = module_dir / "website" / "src" / "css" / "accent.generated.css"
    if accent:
        outputs[accent_path] = accent_css_text(accent)

    print_coverage(rows)
    for conflict in module.conflicts:
        print(f"warning: {conflict}", file=sys.stderr)

    # Written even under --check: the path is a CI artifact directory, not part of the tree.
    if args.coverage_report:
        report_path = Path(args.coverage_report)
        report_path.parent.mkdir(parents=True, exist_ok=True)
        write_generated(report_path, json_text({"version": version, "terms": rows}))
        print(f"Wrote {report_path}")

    if args.check:
        print(f"--check: generated {len(outputs)} file(s) in memory for v{version}, wrote nothing.")
        return 0

    for path, text in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        write_generated(path, text)
        print(f"Wrote {path.relative_to(module_dir)}")
    if not accent and accent_path.exists():
        accent_path.unlink()
        print(f"Removed {accent_path.relative_to(module_dir)} (ACCENT_COLOR is unset)")

    if previous_versions:
        print(
            f"\nv{version} will not be reachable on the site until you also run, right now — not "
            f"deferred to the next release:\n"
            f"    (cd website && npx docusaurus docs:version {version})\n"
            'Skipping this leaves it invisible: not staged, not "current," not in the dropdown.'
        )

    if args.draft_changelog:
        draft_changelog(module, version)
    return 0


def draft_changelog(module: ModuleData, version: str) -> None:
    """Write changelog/v{version}.md, but only when it does not already exist."""
    changelog_dir = module.module_dir / "changelog"
    target = changelog_dir / f"v{version}.md"
    static_dir = module.module_dir / "website" / "static"

    bullets: list[str] = []
    previous_pin = find_previous_pin(static_dir, version)
    if previous_pin is not None:
        previous_ttl = previous_pin / "ont" / "ont.ttl"
        if previous_ttl.exists():
            previous = Graph()
            previous.parse(previous_ttl, format="turtle")
            bullets = diff_bullets(previous, module.merged, module)
            print(f"Diffed against {previous_ttl.relative_to(module.module_dir)}: {len(bullets)} bullet(s)")
    else:
        print("No previous pin found — drafting an initial-release note.")
        bullets = [f"Initial release of {module.title}."]

    if target.exists():
        print(f"{target.relative_to(module.module_dir)} exists — leaving it alone. Draft for review:")
        for bullet in bullets:
            print(f"  - {bullet}")
        return
    changelog_dir.mkdir(parents=True, exist_ok=True)
    write_generated(target, changelog_draft_text(version, module.release_date(), bullets))
    print(f"Wrote {target.relative_to(module.module_dir)} — edit the wording before tagging.")
